---
# Configuration file for Fully Bayesian Forecast Example
# ======================================================
# This file mainly specifies information about the priors used and the
# frequency resolution of the imagined global signal experiment.
#
# It is placed here to make it either easier to consistently change these
# values or because they are used in multiple scripts.
#
#
# FREQUENCY RESOLUTION
# ====================
# The frequency resolution of the experiment in MHz.
frequency_resolution: 1.0
#
#
# PRIORS
# ======
# The priors used for each of global emus parameters.
# Each parameter has its own entry, specifying the prior type and the
# parameters of the prior. low and high are used in place of min and
# max to avoid clashing with python keywords.
priors:
  f_star:
    type: log_uniform
    low: emu_min   # If given emu_min or emu_max, the value is taken from the
    high: emu_max  # minimum or maximum value of GlobalEmu was trained on.
  v_c:
    type: log_uniform
    low: emu_min
    high: 30.0
  f_x:
    type: log_uniform
    low: 0.001
    high: emu_max
  tau:
    type: truncated_gaussian
    mean: 0.054
    std: 0.007
    low: emu_min
    high: emu_max
  alpha:
    type: uniform
    low: emu_min
    high: emu_max
  nu_min:
    type: log_uniform
    low: emu_min
    high: emu_max
  R_mfp:
    type: uniform
    low: emu_min
    high: emu_max
  a_0:
    type: uniform
    low: -10
    high: 10
  a_1:
    type: uniform
    low: -10
    high: 10
  a_2:
    type: uniform
    low: -10
    high: 10
  a_3:
    type: uniform
    low: -10
    high: 10
  a_4:
    type: uniform
    low: -10
    high: 10
  a_5:
    type: uniform
    low: -10
    high: 10
  a_6:
    type: uniform
    low: -10
    high: 10
#
#
# VERIFICATION
# ============
# Number of data sets generate from each model to use when verifying the
# network against PolyChord. Each method is used to evaluate log K and then
# the results are compared.
verification_data_sets_per_model: 1000
#
#
# PLOTTING
# ========
# Parameters that control details of the plots used to visualise the results.
br_evaluations_for_forecast: 1000000
detection_thresholds: ["2 sigma", "3 sigma", "5 sigma"]
parameters_to_plot: ["f_star", "f_x", "tau"]
parameters_to_log: ["f_star", "f_x"]
